### ISSUE TITLE
sent1 missing

### ISSUE THREAD

**Issue by sileod** [ardauzunoglu/paradise#1]
Hi, nice work ! I'd like to add it to [tasksource ](https://github.com/sileod/tasksource)
I noticed that sent1 is allways missing on huggingface
https://huggingface.co/datasets/GGLab/PARADISE/viewer/default/train

is it normal ?
Thanks

**Comment by ardauzunoglu** [comment]
Hi, thanks for reaching out! We follow the data format of Reasoning about Goals, Steps, and Temporal Ordering with WikiHow that can be found [here](https://drive.google.com/drive/folders/19ymhgtXNzD6doSNSQgWyGrdtexiB_b1w). We leave sent1 empty since our task is not a sentence completion task and only requires the question (in our case warning or tip). You can also cite our work as follows if appropriate:

@article{DBLP:journals/corr/abs-2403-03167,
  author       = {Arda Uzunoglu and
                  Abdalfatah Rashid Safa and
                  G{\"{o}}zde G{\"{u}}l Sahin},
  title        = {{PARADISE:} Evaluating Implicit Planning Skills of Language Models
                  with Procedural Warnings and Tips Dataset},
  journal      = {CoRR},
  volume       = {abs/2403.03167},
  year         = {2024},
  url          = {https://doi.org/10.48550/arXiv.2403.03167},
  doi          = {10.48550/ARXIV.2403.03167},
  eprinttype    = {arXiv},
  eprint       = {2403.03167},
  timestamp    = {Wed, 03 Apr 2024 15:23:01 +0200},
  biburl       = {https://dblp.org/rec/journals/corr/abs-2403-03167.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
